name: KitchenOwl
version: "2.1.0"
slug: kitchenowl
description: Self-hosted grocery list and recipe manager
url: https://github.com/meijer3/kitchenowl-ha-addon
arch:
  - aarch64
  - amd64
  - armv7
startup: services
ingress: true
ingress_port: 8080
panel_icon: mdi:food
ports:
  8080/tcp: null
ports_description:
  8080/tcp: Web interface (not needed with Ingress)
options:
  jwt_secret: ""
schema:
  jwt_secret: password
