name: KitchenOwl
version: "1.1.0"
slug: kitchenowl
description: Self-hosted grocery list and recipe manager
url: https://github.com/meijer3/kitchenowl-ha-addon
arch:
  - aarch64
  - amd64
  - armv7
startup: services
ports:
  8080/tcp: null
ports_description:
  8080/tcp: Web interface
options:
  jwt_secret: ""
  port: 8080
schema:
  jwt_secret: password
  port: port
webui: "http://[HOST]:[PORT:8080]"
