name: KitchenOwl
version: "2.1.1"
slug: kitchenowl
description: Self-hosted grocery list and recipe manager
url: https://github.com/meijer3/kitchenowl-ha-addon
arch:
  - aarch64
  - amd64
  - armv7
startup: services
panel_icon: mdi:food
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface
options:
  jwt_secret: ""
schema:
  jwt_secret: password
webui: "http://[HOST]:[PORT:8080]"
