name: KitchenOwl
version: "2.0.6"
slug: kitchenowl
description: Self-hosted grocery list and recipe manager
url: https://github.com/meijer3/kitchenowl-ha-addon
arch:
  - aarch64
  - amd64
  - armv7
startup: services
ingress: true
ingress_port: 8080
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface (also accessible via Home Assistant ingress)
options:
  jwt_secret: ""
schema:
  jwt_secret: password
webui: "http://[HOST]:[PORT:8080]"
