name: KitchenOwl
version: "1.0.0"
slug: kitchenowl
description: Self-hosted grocery list and recipe manager
url: https://github.com/meijer3/kitchenowl-ha-addon
arch:
  - aarch64
  - amd64
  - armv7
startup: services
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Web interface
options:
  jwt_secret: ""
schema:
  jwt_secret: password
webui: http://[HOST]:8080
