name: KitchenOwl
version: "2.0.1"
slug: kitchenowl
description: Self-hosted grocery list and recipe manager
url: https://github.com/meijer3/kitchenowl-ha-addon
arch:
  - aarch64
  - amd64
  - armv7
startup: services
ports:
  5000/tcp: null
ports_description:
  5000/tcp: Web interface
options:
  jwt_secret: ""
  port: 5000
schema:
  jwt_secret: password
  port: port
webui: "http://[HOST]:[PORT:5000]"
